WebMangaAspCore/Controllers/ProduitController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebmangaAspCore.Models.Persistance;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace WebMangaAspCore.Controllers
{
    public class ProduitController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult AugmenterPrix()
        {

            string prix = Request.Form["prix"];
            float p = Int32.Parse(prix);
            prix = p.ToString();
            String param = "val;" + prix.Replace(',', '.');
            ArrayList allParams = new ArrayList();
            ViewBag.ValueAugm = Math.Round(p * 100, 1, MidpointRounding.ToEven).ToString();
            allParams.Add(param);

            DBInterface.Procedure_Stockee("augmenterPrix", allParams);

            return RedirectToAction("Index", "Manga"); ;
        }
    }
}

WebMangaAspCore/Views/Shared/_LayoutManga.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebManga</title>

    <environment include="Development">
       
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/site.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/mangas.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    </environment>
    

</head>
<body>

    <partial name="~/Views/Shared/_Navigation.cshtml" />
    <div class="container body-content">
        @RenderBody()

    </div>


    <!--<footer class="container-fluid text-center">
        <div class="footer-copyright text-center py-3">
            © 2020 Copyright:CV
            <p> @DateTime.Now.Year - Web Manga Application</p>
        </div>
    </footer>-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WebMangaAspCore/Views/Shared/_navigation.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

           
            @Html.ActionLink("Web Manga", "About", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Accès membre<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li class="dropdown-header">Application</li>
                        <li class="dropdown-header">----------</li>
                        @if (!WebmangaAspCore.Models.Metier.Utilisateur.IsConnected())
                        {
                            <li role="separator" class="divider"></li>
                            <li><a class="nav-link text-dark" asp-area="Connexion" asp-controller="Connexion" asp-action="Index">Connexion</a></li>
                        }
                        else
                        {
                            <li role="separator" class="divider"></li>
                            <li><a class="nav-link text-dark" asp-area="Déconnexion" asp-controller="Connexion" asp-action="Logout">Déconnexion</a></li>
                        }
                        </ul>
                </li>
                @if (WebmangaAspCore.Models.Metier.Utilisateur.IsConnected())
                {
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Interroger<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-header">Fiches</li>
                            <li role="separator" class="divider"></li>
                            <li><a class="nav-link text-dark" asp-area="Liste des Mangas" asp-controller="Manga" asp-action="Index">liste des Manga</a></li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Gérer<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-header">Gestion</li>
                            <li role="separator" class="divider"></li>
                            <li><a class="nav-link text-dark" asp-area="Ajouter Manga" asp-controller="Client" asp-action="Index">Ajouter Manga</a></li>
                            <li role="separator" class="divider"></li>
                            <li class="dropdown-header">Produits</li>
                            <li role="separator" class="divider"></li>
                            <li><a class="nav-link text-dark" asp-area="Augmenter Prix" asp-controller="Produit" asp-action="Index">AugmenterPrix</a></li>
                        </ul>
                    </li>
                }
            </ul>
        </div>
    </div>
</div>